version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: cotti-whatsapp-bot
    restart: unless-stopped
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./temp:/usr/src/app/temp
    # If you want to use a .env file with docker-compose, uncomment the next line
    # env_file:
    #   - .env
